# Generated by Selenium IDE              
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestLoginnegativo():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_loginnegativo(self):
    self.driver.get("https://www.giulianaflores.com.br/")
    self.driver.set_window_size(872, 654)
    element = self.driver.find_element(By.ID, "carrinho-display")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()

    # Espera explícita para garantir que o elemento está visível e clicável
    self.driver.find_element(By.CSS_SELECTOR, "#perfil-hidden > img").click()
    self.driver.find_element(By.CSS_SELECTOR, "#UrlLogin > a").click()
    self.driver.find_element(By.ID, "ContentSite_txtEmail").click()
    self.driver.find_element(By.ID, "ContentSite_txtEmail").send_keys("joaomaria@hotmail.com") # Email certo
    self.driver.find_element(By.ID, "ContentSite_txtPassword").click()
    self.driver.find_element(By.ID, "ContentSite_txtPassword").send_keys("61039852555")         # Senha Incorreta   
    self.driver.find_element(By.ID, "ContentSite_ibtContinue").click()
    self.driver.find_element(By.ID, "ContentSite_txtEmail").click()
    self.driver.find_element(By.ID, "ContentSite_txtEmail").send_keys("mariajoao@hotmail.com")    # Email Incorreto
    self.driver.find_element(By.ID, "ContentSite_txtPassword").click()
    self.driver.find_element(By.ID, "ContentSite_txtPassword").send_keys("JM61093188*")          # Senha certa
    self.driver.find_element(By.ID, "ContentSite_ibtContinue").click()
    self.driver.find_element(By.CSS_SELECTOR, ".aviso-erro").click()                      ## Aviso de Erro 
    time.sleep(10)
    self.driver.find_element(By.ID, "ContentSite_ibtContinue").click()
