# Generated by Selenium IDE
# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestUntitled():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_untitled(self):
    self.driver.get("https://www.giulianaflores.com.br/")
    self.driver.set_window_size(1296, 688)
    self.driver.execute_script("window.scrollTo(0,1600)")
    self.driver.find_element(By.CSS_SELECTOR, ".product-container:nth-child(3) .owl-item:nth-child(1) .title-item:nth-child(2)").click()
    self.driver.execute_script("window.scrollTo(0,236)")
    self.driver.execute_script("window.scrollTo(0,300.6666564941406)")
    self.driver.execute_script("window.scrollTo(0,599.3333129882812)")
    self.driver.find_element(By.ID, "ContentSite_txtZip").click()
    self.driver.find_element(By.ID, "ContentSite_txtZip").send_keys("03982")
    self.driver.find_element(By.ID, "ContentSite_txtZipComplement").send_keys("150")
    self.driver.execute_script("window.scrollTo(0,400.6666564941406)")
    self.driver.execute_script("window.scrollTo(0,407.3333435058594)")
    self.driver.find_element(By.ID, "ContentSite_lbtBuy").click()
    self.driver.find_element(By.CSS_SELECTOR, ".titulo-dept").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".titulo-dept title-defaut-interna").text == "MEU CARRINHO"
    assert self.driver.find_element(By.LINK_TEXT, "Orquídea Pink Presente - Te Amo").text == "Orquídea Pink Presente - Te Amo"
    assert self.driver.find_element(By.CSS_SELECTOR, ".precoPor_basket:nth-child(3)").text == "R$ 89,90"
    assert self.driver.find_element(By.ID, "ContentSite_Basketcontrol1_rptBasket_rptBasketItems_0_lbtRemoveProduct_0").text == "Excluir"
    self.driver.find_element(By.ID, "ContentSite_Basketcontrol1_rptBasket_rptBasketItems_0_lbtRemoveProduct_0").click()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
